### ISSUE TITLE
JBU training error

### ISSUE THREAD

**Issue by qyun29** [NVlabs/pacnet#19]
Hello, i want to apply your PacConvTransposed2d to my model. But when do training,
Traceback (most recent call last):
  File "C:\Users\Qyun\anaconda3\envs\pix_net\lib\site-packages\torch\autograd\function.py", line 189, in wrapper
    outputs = fn(ctx, *args)
  File "C:\projects\pacnet-master\pac.py", line 286, in backward
    ctx._backend.Im2Col_updateGradInput(ctx._backend.library_state,
  File "C:\Users\Qyun\anaconda3\envs\pix_net\lib\site-packages\torch\_thnn\utils.py", line 27, in __getattr__
    raise NotImplementedError
NotImplementedError
this error occurred.
and the same error is occurred when i do training task_jointUpsampling. How can I solve this problem?

**Comment by suhangpro** [comment]
This is due to an incompatible pytorch version. The code was originally developed for pytorch 0.4. You can try the branch "th14". There were some related discussions in #14
