### ISSUE TITLE
Error in unittest when testing PacConv

### ISSUE THREAD

**Issue by toxicmender** [NVlabs/pacnet#2]
## Setup:
* Pytorch Build: Pytorch 1.1 (Torchvision 0.3.0)
* OS: Pop_OS (Ubuntu Disco Dingo Derivative)
* Package: pip (instead of recommended conda)
* Python: python 3.7
* CUDA: CUDA 10 (with nvidia-driver-418)

```sh
.../home/danish/Documents/Repositories/pacnet/pac.py:447: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  output = output / (norm + torch.tensor(empty_mask, dtype=input.dtype, device=input.device))
............E.....
======================================================================
ERROR: test_kernel_two_impl_match (test_pac.PacConvTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/danish/Documents/Repositories/pacnet/test_pac.py", line 309, in test_kernel_two_impl_match
    out.sum().backward()
  File "/home/danish/Documents/Repositories/pacnet/env/lib/python3.7/site-packages/torch/tensor.py", line 107, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/danish/Documents/Repositories/pacnet/env/lib/python3.7/site-packages/torch/autograd/__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "/home/danish/Documents/Repositories/pacnet/env/lib/python3.7/site-packages/torch/autograd/function.py", line 77, in apply
    return self._forward_cls.backward(self, *args)
  File "/home/danish/Documents/Repositories/pacnet/env/lib/python3.7/site-packages/torch/autograd/function.py", line 189, in wrapper
    outputs = fn(ctx, *args)
  File "/home/danish/Documents/Repositories/pacnet/pac.py", line 126, in backward
    grad_diff = grad.expand_as(cols) * (2 * diff)
RuntimeError: CUDA out of memory. Tried to allocate 576.00 MiB (GPU 0; 3.95 GiB total capacity; 2.02 GiB already allocated; 453.06 MiB free; 586.00 MiB cached)

----------------------------------------------------------------------
Ran 21 tests in 32.108s

FAILED (errors=1)
```

**Comment by suhangpro** [comment]
This likely does not indicate any real issue, but rather the GPU memory not large enough for that test case. To run the experiments, we suggest a GPU with larger (e.g. 11GB) memory.

**Comment by toxicmender** [comment]
Yeah I realised that but I didn't know how to ask questions about the test cases. So had opened an issue here. Is there a way to run the test case individually (I mean module by module). That may help someone like me to run it on lower memory GPU.

**Comment by suhangpro** [comment]
@toxicmender This will run a single test case: `python test_pac.py PacConvTest.test_conv_forward_const_kernel`

**Comment by toxicmender** [comment]
Thanks a lot.
